DROP TABLE PCATEGORY CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE USERES CASCADE CONSTRAINTS;
DROP TABLE DELIVERYBOY CASCADE CONSTRAINTS;
DROP TABLE BILL CASCADE CONSTRAINTS;
DROP TABLE BILLPRODUCT CASCADE CONSTRAINTS;
DROP TABLE BOYORDER CASCADE CONSTRAINTS;

CREATE TABLE PCATEGORY
(CategoryName VARCHAR2(50) PRIMARY KEY);

CREATE TABLE PRODUCT
(ProductName VARCHAR2(50) PRIMARY KEY,
 Description VARCHAR2(100),
 Price NUMBER,
 Quantity NUMBER,
 CategoryName VARCHAR(50),
 CONSTRAINTS fkProduct FOREIGN KEY(CategoryName) REFERENCES PCATEGORY(CategoryName));


CREATE TABLE USERES
(UserName VARCHAR2(50) PRIMARY KEY,
 UserPassword VARCHAR2(50),
 FullName VARCHAR(50),
 MobileNumber VARCHAR(12),
 USERTYPE VARCHAR2(20));

 CREATE TABLE DELIVERYBOY
(BoyName VARCHAR2(50) PRIMARY KEY,
 MobileNumber VARCHAR2(12),
 Address VARCHAR(50),
 Age NUMBER,
 STATUS VARCHAR2(50));
 
 
 CREATE TABLE BILL
(BillId NUMBER PRIMARY KEY,
 BillDate DATE,
 Customer VARCHAR(50)  REFERENCES USERES(UserName),
 Deliveryboy VARCHAR(50) REFERENCES DELIVERYBOY(BoyName),
 TotalPrice NUMBER);
 
 
 CREATE TABLE BILLPRODUCT
(BILLID NUMBER REFERENCES BILL(BILLID),
 PRODUCTNAME VARCHAR2(50) REFERENCES PRODUCT(ProductName),
 CONSTRAINTS pkBillProduct PRIMARY KEY(BILLID, PRODUCTNAME));

CREATE TABLE BOYORDER
(BILLID NUMBER REFERENCES BILL(BILLID),
 BOYNAME VARCHAR2(50) REFERENCES DELIVERYBOY(BOYNAME),
 STATUS VARCHAR2(1),
 CONSTRAINTS pkBillOrder PRIMARY KEY(BILLID, BOYNAME));

INSERT INTO PCATEGORY VALUES ('Clothes');
INSERT INTO PCATEGORY VALUES ('Phones');
INSERT INTO PCATEGORY VALUES ('Electronics');
INSERT INTO PCATEGORY VALUES ('Computing');

INSERT INTO PRODUCT VALUES ('Shirt', 'Style: super comfortable, relaxed fit, lightweight and fashionable.', 200, 20, 'Clothes');
INSERT INTO PRODUCT VALUES ('Shoes', 'Upper Material:Genuine Leather', 150, 10, 'Clothes');
INSERT INTO PRODUCT VALUES ('T-Shirt', 'Men Crew Neck T-Shirt with Short Sleeves - DARK BLACK', 120, 15, 'Clothes');
INSERT INTO PRODUCT VALUES ('Jacket', 'Cotton material, Zipper closure, Long Sleeve and Side pockets', 200, 5, 'Clothes');

COMMIT;